apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      name: myapp1-pod
      labels:
        app: myapp1
    spec:
      containers:
      - name: myapp1-container
        image: stacksimplify/kubenginx:3.0.0 #gcr.io/google-containers/busybox
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
