apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # storage: 4Gi
      storage: 8Gi
  storageClassName: gke-pd-standard-rwo-sc # premium-rwo #standard-rwo
